apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rdv-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/M4STERPIECE77K/hop-manage.git
    targetRevision: main
    path: backend/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: rdv-prod
